# Generated by Django 6.0.5 on 2026-06-26 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborations', '0002_collaborationinvite_team_teammember'),
        ('projects', '0006_workproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationinvite',
            name='proposed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='collaborationinvite',
            name='response_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='collaborationinvite',
            name='selected_gig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.gig'),
        ),
    ]
