# Generated by Django 6.0.5 on 2026-06-26 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborations', '0003_collaborationinvite_proposed_price_and_more'),
        ('projects', '0006_workproposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='gig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.gig'),
        ),
    ]
