# Generated by Django 6.0.5 on 2026-05-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='revisions',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
