# Generated by Django 6.0.5 on 2026-06-04 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_projectrolerequirement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='project',
            name='job_category',
        ),
    ]
