# Generated by Django 6.0.5 on 2026-06-27 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborations', '0004_alter_teammember_gig'),
        ('projects', '0006_workproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='collaborations.team'),
        ),
    ]
