# Generated by Django 6.0.5 on 2026-06-30 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_application_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='workproposal',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='projects.application'),
        ),
    ]
