# Generated by Django 6.0.5 on 2026-07-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_workproposal_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='workproposal',
            name='counter_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
